name: Client Unit Testing
on: [push, pull_request]
jobs:
  jest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12]
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node}}
    - run: yarn install
      working-directory: client
    - run: yarn jest
      working-directory: client