name: Client linting
on:
  push:
    paths:
      - 'client/**'
      - '.github/workflows/js_lint.yaml'
  pull_request:
    paths:
      - 'client/**'
      - '.github/workflows/js_lint.yaml'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  client-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/setup-node.yaml
      - run: yarn install --frozen-lockfile
        working-directory: client
      - name: Run ESLint
        run: yarn run eslint
        working-directory: client
      - name: Run prettier checks
        run: yarn run format-check
        working-directory: client
